# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Test
    #  run: mvn test
    - name: pom goal of help plugin(tool)	Displays the effective POM as an XML for this build
      run: mvn help:effective-pom
    - name: Lists all Maven dependencies from our project
      run: mvn dependency:list
    - name: Compiles the source code of the projects.
      run: mvn compile
    - name: Build with Maven
      run: mvn clean package

